name: Run tests against changes

on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ['3.8', '3.9', '3.10']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update -qq && sudo apt-get install -qq libglib2.0-0 libgl1 libfontconfig1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Update pip
        run: pip install -U pip

      - name: Install package
        run: pip install -r requirements.txt -r requirements-dev.txt .

      - name: Run tests
        env:
          QT_QPA_PLATFORM: offscreen
        run: python3 -m pytest
